/** FAQs for product and specialty pages, per language. Rendered as a visible section and as FAQPage structured data. */
export type Faq = { q: string; a: string };
export type FaqSet = { title: string; items: Faq[] };

const T = { en: "Frequently asked questions", nl: "Veelgestelde vragen", de: "Häufige Fragen" };

export const FAQS: Record<string, Record<string, FaqSet>> = {
  en: {
    "/product": { title: T.en, items: [
      { q: "What does Optavius do?", a: "Optavius answers your practice's phone with an AI voice agent. It answers questions, books, moves and cancels appointments, gives order status and escalates urgent symptoms by your protocol. The same agent also handles web chat, email, SMS and WhatsApp." },
      { q: "Does it replace our front desk?", a: "No. It takes the routine calls so your team has time for the patient in front of them. Anything clinical, urgent or unusual goes to a person with the transcript attached." },
      { q: "Which languages does it speak?", a: "English, Dutch and German today, with the accent and phrasing of the region. Callers can switch language mid-call." },
      { q: "What happens with an urgent symptom?", a: "The agent follows the red-flag list your clinical lead approved. It tells the caller what to do, routes to the on-call number if that is the rule, and sends a summary to your team within seconds." },
      { q: "How long does it take to go live?", a: "Most practices are live within 48 hours. You forward your number, approve the pathways and see the first calls in the console the same week." },
      { q: "How do we know it is doing a good job?", a: "Every call is logged with a transcript and an outcome. A supervising agent scores a sample of conversations on accuracy and tone, and you see the scores in the console." },
    ] },
    "/product/console": { title: T.en, items: [
      { q: "What is the console?", a: "The place where you see everything the agents do: every call, booking and escalation, a morning brief, and a bar where you change rules in plain language." },
      { q: "What is in the morning brief?", a: "Calls answered overnight, bookings made, escalations, anything unusual, and what needs your decision today. It is written for you each morning." },
      { q: "Can I pause an agent?", a: "Yes, in one click, per agent and per location. Calls then ring through to your team until you switch it back on." },
      { q: "Who can use the console?", a: "Unlimited users. You decide who sees what, per location and per role. Every change is logged with the person who made it." },
      { q: "Is there an app?", a: "Yes. The same console as an app, with push notifications for approvals and the morning brief." },
      { q: "Can I change a rule without calling you?", a: "Yes. Type it in the command bar, for example \"stop booking Dr. Alvarez on Fridays\". The change carries a reference and can be undone." },
    ] },
    "/product/ask-optavius": { title: T.en, items: [
      { q: "What does Ask Optavius connect to?", a: "Your calendar, phone system, practice management export and referral mailbox, read-only. Standard connectors take a day." },
      { q: "Is it really free?", a: "Yes, for 90 days. After that it is included with every live agent. No card is needed to start." },
      { q: "Can it change anything in our systems?", a: "No. Ask Optavius never writes to your systems. It reads, answers and reports." },
      { q: "What kind of questions can I ask?", a: "Anything about your own practice: no-shows per location, unanswered calls last week, referral backlog, revenue booked next month. Every answer cites the system and sync time it came from." },
      { q: "Where is our data stored?", a: "In the region of your practice: the EU for European practices, the US for American practices. Encrypted in transit and at rest." },
      { q: "What happens after the 90 days?", a: "You keep it with any live agent, or the connection is closed and the data deleted within 30 days." },
    ] },
    "/product/agents": { title: T.en, items: [
      { q: "What is an agent?", a: "One job, done end to end. The front desk agent answers and books. The recall agent finds patients who are due and calls until they are booked. Each one reports to you every day." },
      { q: "Which agents can I hire?", a: "Front desk, booking, order status, recall and reminders, no-show recovery, waitlist, referral intake, intake and forms, web chat and email, post-op follow-up, order review and patient billing." },
      { q: "What is shadow mode?", a: "A week on real calls without acting. You see everything the agent would have said and done, scored by the reviewer, before you switch it on." },
      { q: "How do I add an agent?", a: "In a click. The agent proposes rules from your practice data, you amend them in plain language and approve. Billing starts the day it goes live." },
      { q: "Do agents work across locations?", a: "Yes. One agent can cover several locations with their own hours, providers and rules, and you see each location separately in the console." },
      { q: "Can I switch an agent off?", a: "Any time, in one click. Calls ring through to your team and nothing is lost." },
    ] },
    "/product/integrations": { title: T.en, items: [
      { q: "Do I need to change my phone system?", a: "No. Calls are forwarded to Optavius from any phone system: RingCentral, Zoom Phone, Twilio, Vonage, a PBX or a SIP trunk. Your number stays the same." },
      { q: "Which practice systems do you integrate with?", a: "RevolutionEHR, Eyefinity, Crystal PM, Compulink, MaximEyes, ModMed, Nextech, Epic and ChipSoft via API or FHIR, plus Google Calendar, Outlook and Cal.com." },
      { q: "Can we start without an EHR integration?", a: "Yes. Most practices start with the calendar only and connect the EHR later. Bookings are confirmed to the patient by text either way." },
      { q: "How are bookings written into our system?", a: "Two-way sync. Every booking is read back before it is confirmed to the patient, so there are no double bookings and no manual entry." },
      { q: "Is patient data safe?", a: "Records are FHIR-aligned, encrypted with AES-256 at rest and TLS 1.3 in transit, and stored in your region. Access is read-only first and write access is granted per agent, per action." },
      { q: "We use a system that is not on the list. Can it connect?", a: "Any system with an open API or an MCP server can be connected, scoped per practice." },
    ] },
    "/specialties/ophthalmology": { title: T.en, items: [
      { q: "How does the agent handle flashes, floaters or sudden vision loss?", a: "It follows your red-flag protocol: it asks the questions your clinical lead approved, offers a same-day urgent slot or routes to on-call, and sends your team a summary within seconds." },
      { q: "Can it book the right visit type?", a: "Yes. It knows a cataract evaluation from an injection visit or a post-op check, books the right provider and slot length, and confirms by text." },
      { q: "Does it handle referrals?", a: "The referral intake agent reads each referral, checks what is missing, chases it and calls the patient to book. Nothing waits in a mailbox." },
      { q: "Can it call surgical patients after their procedure?", a: "Yes. The post-op agent calls every surgical patient, asks your questions and flags pain, redness or blurred vision to your team." },
      { q: "We have several locations. Does that work?", a: "Yes. One agent covers all locations with their own hours and providers, and you see each one separately in the console." },
      { q: "Does it give medical advice?", a: "No. It answers, books, routes and escalates. Clinical questions go to your team with the transcript." },
    ] },
    "/specialties/optometry": { title: T.en, items: [
      { q: "Can it tell patients whether their glasses are ready?", a: "Yes. It reads the order status from your system and tells the caller whether the glasses, lenses or order are ready, with the promise date if not." },
      { q: "Does it handle contact lens reorders?", a: "Yes. It verifies the prescription, confirms the lenses and ships to the address on file, or books a check if the prescription has expired." },
      { q: "What about insurance questions?", a: "It answers which plans you accept, what an exam costs and what is covered, from the scripts you approve." },
      { q: "Can it answer after hours?", a: "Yes, all night and all weekend. Callers book, reorder or leave a request, and your team finds it in the morning brief." },
      { q: "Does it work for a multi-store chain?", a: "Yes. Each store has its own hours, staff and calendar, and the agent knows which is which." },
      { q: "Will it sound like our store?", a: "You approve the greeting, the tone and the scripts. It says your store name and follows your rules." },
    ] },
    "/specialties/dermatology": { title: T.en, items: [
      { q: "How does it triage a changing mole or a sudden rash?", a: "It asks the questions on your urgent-lesion list, offers an urgent slot or routes to on-call by your protocol, and sends a summary to your team." },
      { q: "Can it separate medical and cosmetic bookings?", a: "Yes. It books the right visit type, provider and slot length for each, and applies your deposit or cancellation rules for cosmetic visits." },
      { q: "Does it handle prescription refill requests?", a: "It takes the request, checks the patient's details and passes it to your team for approval. It never issues a prescription itself." },
      { q: "Can it fill cancelled slots?", a: "Yes. When a slot opens, the waitlist agent works down your list until it is filled." },
      { q: "What about pre-visit instructions?", a: "It sends preparation instructions and forms by text or email and confirms the patient is ready before the visit." },
      { q: "Is it compliant with health data rules?", a: "HIPAA in the US, GDPR in Europe, with data stored in your region and every call logged and auditable." },
    ] },
    "/specialties/veterinary": { title: T.en, items: [
      { q: "What happens when an owner calls with an emergency?", a: "The agent follows your emergency protocol: it tells the owner what to do now, routes to the on-call vet or emergency clinic, and sends your team a summary." },
      { q: "Can it book different appointment types?", a: "Yes. Vaccinations, check-ups, surgery consults and grooming, with the right length and the right vet, for dogs, cats and other animals you specify." },
      { q: "Does it handle medication and food refills?", a: "It takes refill requests, checks the animal's record and passes them to your team for approval, then tells the owner when to pick up." },
      { q: "Can it answer after hours?", a: "Yes. Routine questions and bookings are handled all night, and emergencies are routed by your protocol." },
      { q: "Does it send reminders?", a: "Yes. Vaccination and check-up reminders by call or text, and it books when the owner says yes." },
      { q: "Will it know our vets and their schedules?", a: "Yes. It reads your calendar and books each vet according to their own hours and rules." },
    ] },
  },
  nl: {
    "/product": { title: T.nl, items: [
      { q: "Wat doet Optavius?", a: "Optavius neemt de telefoon van uw praktijk op met een AI-spraakagent. Die beantwoordt vragen, plant, verzet en annuleert afspraken, geeft bestelstatus door en escaleert spoedklachten volgens uw protocol. Dezelfde agent handelt ook webchat, e-mail, sms en WhatsApp af." },
      { q: "Vervangt het onze balie?", a: "Nee. Het neemt de routineoproepen over, zodat uw team tijd heeft voor de patiënt aan de balie. Alles wat klinisch, spoedeisend of ongewoon is, gaat naar een medewerker, met het transcript erbij." },
      { q: "Welke talen spreekt het?", a: "Nederlands, Engels en Duits, met de klank en formulering van de regio. Bellers kunnen midden in het gesprek van taal wisselen." },
      { q: "Wat gebeurt er bij een spoedklacht?", a: "De agent volgt de alarmsymptoomlijst die uw klinisch verantwoordelijke heeft goedgekeurd. Hij vertelt de beller wat te doen, schakelt door naar het spoednummer als dat de regel is, en stuurt binnen seconden een samenvatting naar uw team." },
      { q: "Hoe snel zijn we live?", a: "De meeste praktijken binnen 48 uur. U schakelt uw nummer door, keurt de routes goed en ziet dezelfde week de eerste gesprekken in de console." },
      { q: "Hoe weten we dat het goed gaat?", a: "Elk gesprek wordt vastgelegd met transcript en uitkomst. Een toezichthoudende agent beoordeelt een steekproef op juistheid en toon, en u ziet de scores in de console." },
    ] },
    "/product/console": { title: T.nl, items: [
      { q: "Wat is de console?", a: "De plek waar u alles ziet wat de agents doen: elk gesprek, elke afspraak en escalatie, een ochtendbriefing en een balk waarin u regels in gewone taal aanpast." },
      { q: "Wat staat er in de ochtendbriefing?", a: "Gesprekken van de nacht, gemaakte afspraken, escalaties, alles wat opviel en wat vandaag uw beslissing nodig heeft. Elke ochtend voor u geschreven." },
      { q: "Kan ik een agent pauzeren?", a: "Ja, met één klik, per agent en per locatie. Oproepen gaan dan naar uw team tot u hem weer inschakelt." },
      { q: "Wie kan de console gebruiken?", a: "Onbeperkt gebruikers. U bepaalt wie wat ziet, per locatie en per rol. Elke wijziging wordt vastgelegd met de naam van wie hem deed." },
      { q: "Is er een app?", a: "Ja. Dezelfde console als app, met pushmeldingen voor goedkeuringen en de ochtendbriefing." },
      { q: "Kan ik een regel aanpassen zonder u te bellen?", a: "Ja. Typ het in de opdrachtbalk, bijvoorbeeld \"plan dr. Alvarez niet meer in op vrijdag\". De wijziging krijgt een referentie en is terug te draaien." },
    ] },
    "/product/ask-optavius": { title: T.nl, items: [
      { q: "Waarmee koppelt Ask Optavius?", a: "Uw agenda, telefoonsysteem, export uit het praktijksysteem en de verwijzingsmailbox, alleen-lezen. Standaardkoppelingen zijn in een dag gelegd." },
      { q: "Is het echt gratis?", a: "Ja, 90 dagen. Daarna is het inbegrepen bij elke actieve agent. U heeft geen kaart nodig om te starten." },
      { q: "Kan het iets in onze systemen wijzigen?", a: "Nee. Ask Optavius schrijft nooit in uw systemen. Het leest, beantwoordt en rapporteert." },
      { q: "Wat voor vragen kan ik stellen?", a: "Alles over uw eigen praktijk: no-shows per locatie, onbeantwoorde oproepen vorige week, verwijzingsachterstand, geboekte omzet volgende maand. Elk antwoord vermeldt het systeem en het synchronisatiemoment." },
      { q: "Waar staan onze gegevens?", a: "In de regio van uw praktijk: de EU voor Europese praktijken, de VS voor Amerikaanse. Versleuteld tijdens transport en in opslag." },
      { q: "Wat gebeurt er na 90 dagen?", a: "U houdt het bij elke actieve agent, of de koppeling wordt gesloten en de gegevens binnen 30 dagen verwijderd." },
    ] },
    "/product/agents": { title: T.nl, items: [
      { q: "Wat is een agent?", a: "Eén taak, van begin tot eind. De balie-agent beantwoordt en plant in. De recall-agent zoekt patiënten die aan de beurt zijn en belt tot ze zijn ingepland. Elke agent rapporteert dagelijks aan u." },
      { q: "Welke agents kan ik inzetten?", a: "Balie, afspraken, bestelstatus, recall en herinneringen, no-show-herstel, wachtlijst, verwijzingsintake, intake en formulieren, webchat en e-mail, nazorg na een ingreep, ordercontrole en facturatie." },
      { q: "Wat is schaduwmodus?", a: "Een week op echte gesprekken zonder te handelen. U ziet alles wat de agent zou hebben gezegd en gedaan, beoordeeld door de reviewer, voordat u hem inschakelt." },
      { q: "Hoe voeg ik een agent toe?", a: "Met één klik. De agent stelt regels voor op basis van uw praktijkgegevens, u past ze in gewone taal aan en keurt goed. Facturatie begint op de dag dat hij live gaat." },
      { q: "Werken agents over meerdere locaties?", a: "Ja. Eén agent bedient meerdere locaties met eigen tijden, behandelaars en regels, en u ziet elke locatie apart in de console." },
      { q: "Kan ik een agent uitzetten?", a: "Altijd, met één klik. Oproepen gaan naar uw team en er gaat niets verloren." },
    ] },
    "/product/integrations": { title: T.nl, items: [
      { q: "Moet ik mijn telefoonsysteem vervangen?", a: "Nee. Oproepen worden vanuit elk telefoonsysteem doorgeschakeld naar Optavius: RingCentral, Zoom Phone, Twilio, Vonage, een centrale of een SIP-trunk. Uw nummer blijft hetzelfde." },
      { q: "Met welke praktijksystemen koppelt u?", a: "RevolutionEHR, Eyefinity, Crystal PM, Compulink, MaximEyes, ModMed, Nextech, Epic en ChipSoft via API of FHIR, plus Google Agenda, Outlook en Cal.com." },
      { q: "Kunnen we starten zonder EPD-koppeling?", a: "Ja. De meeste praktijken starten met alleen de agenda en koppelen het EPD later. Afspraken worden hoe dan ook per sms aan de patiënt bevestigd." },
      { q: "Hoe komen afspraken in ons systeem?", a: "Tweerichtingssynchronisatie. Elke afspraak wordt teruggelezen voordat hij aan de patiënt wordt bevestigd, dus geen dubbele boekingen en geen handmatige invoer." },
      { q: "Zijn patiëntgegevens veilig?", a: "Gegevens zijn FHIR-conform, versleuteld met AES-256 in opslag en TLS 1.3 tijdens transport, en opgeslagen in uw regio. Toegang is eerst alleen-lezen; schrijfrechten worden per agent en per actie verleend." },
      { q: "Ons systeem staat niet in de lijst. Kan het toch?", a: "Elk systeem met een open API of een MCP-server kan worden gekoppeld, afgebakend per praktijk." },
    ] },
    "/specialties/ophthalmology": { title: T.nl, items: [
      { q: "Wat doet de agent bij lichtflitsen, vlekken of plotseling verlies van zicht?", a: "Hij volgt uw alarmsymptoomprotocol: stelt de vragen die uw klinisch verantwoordelijke heeft goedgekeurd, biedt dezelfde dag een spoedplek of schakelt door naar de dienstdoende arts, en stuurt uw team binnen seconden een samenvatting." },
      { q: "Plant het het juiste type afspraak?", a: "Ja. Het kent het verschil tussen een cataractconsult, een injectie en een controle na een ingreep, plant de juiste behandelaar en duur en bevestigt per sms." },
      { q: "Handelt het verwijzingen af?", a: "De verwijzingsintake-agent leest elke verwijzing, controleert wat ontbreekt, vraagt het op en belt de patiënt om in te plannen. Niets blijft in een mailbox liggen." },
      { q: "Kan het patiënten na een operatie bellen?", a: "Ja. De nazorg-agent belt elke geopereerde patiënt, stelt uw vragen en meldt pijn, roodheid of wazig zien aan uw team." },
      { q: "We hebben meerdere locaties. Werkt dat?", a: "Ja. Eén agent bedient alle locaties met eigen tijden en behandelaars, en u ziet elke locatie apart in de console." },
      { q: "Geeft het medisch advies?", a: "Nee. Het beantwoordt, plant, routeert en escaleert. Klinische vragen gaan met het transcript naar uw team." },
    ] },
    "/specialties/optometry": { title: T.nl, items: [
      { q: "Kan het klanten vertellen of hun bril klaar is?", a: "Ja. Het leest de bestelstatus uit uw systeem en vertelt de beller of de bril, lenzen of bestelling klaar is, en anders de verwachte datum." },
      { q: "Handelt het nabestellingen van contactlenzen af?", a: "Ja. Het controleert de sterkte, bevestigt de lenzen en verzendt naar het bekende adres, of plant een controle als de sterkte verlopen is." },
      { q: "En vragen over vergoedingen?", a: "Het beantwoordt welke verzekeraars u accepteert, wat een oogmeting kost en wat vergoed wordt, op basis van de scripts die u goedkeurt." },
      { q: "Neemt het buiten openingstijden op?", a: "Ja, de hele nacht en het hele weekend. Bellers plannen, bestellen na of laten een verzoek achter, en uw team vindt het in de ochtendbriefing." },
      { q: "Werkt het voor een keten met meerdere winkels?", a: "Ja. Elke winkel heeft eigen tijden, medewerkers en agenda, en de agent weet welke welke is." },
      { q: "Klinkt het als onze winkel?", a: "U keurt de begroeting, de toon en de scripts goed. Het noemt uw winkelnaam en volgt uw regels." },
    ] },
    "/specialties/dermatology": { title: T.nl, items: [
      { q: "Hoe gaat het om met een veranderende moedervlek of plotselinge uitslag?", a: "Het stelt de vragen van uw lijst met urgente huidafwijkingen, biedt een spoedplek of schakelt door volgens uw protocol, en stuurt een samenvatting naar uw team." },
      { q: "Kan het medische en cosmetische afspraken scheiden?", a: "Ja. Het plant voor elk het juiste type, de juiste behandelaar en duur, en past uw aanbetalings- of annuleringsregels voor cosmetische afspraken toe." },
      { q: "Handelt het herhaalrecepten af?", a: "Het neemt het verzoek aan, controleert de gegevens van de patiënt en legt het ter goedkeuring bij uw team. Het schrijft zelf nooit een recept uit." },
      { q: "Kan het geannuleerde plekken opvullen?", a: "Ja. Als er een plek vrijkomt, werkt de wachtlijst-agent uw lijst af tot hij gevuld is." },
      { q: "En instructies vóór het bezoek?", a: "Het stuurt voorbereidingsinstructies en formulieren per sms of e-mail en bevestigt vóór het bezoek dat de patiënt er klaar voor is." },
      { q: "Voldoet het aan de regels voor gezondheidsgegevens?", a: "AVG in Europa, HIPAA in de VS, met gegevens in uw regio en elk gesprek vastgelegd en controleerbaar." },
    ] },
    "/specialties/veterinary": { title: T.nl, items: [
      { q: "Wat gebeurt er als een eigenaar belt met een noodgeval?", a: "De agent volgt uw noodprotocol: vertelt de eigenaar wat nu te doen, schakelt door naar de dienstdoende dierenarts of spoedkliniek, en stuurt uw team een samenvatting." },
      { q: "Kan het verschillende soorten afspraken plannen?", a: "Ja. Vaccinaties, controles, operatieconsulten en trimmen, met de juiste duur en de juiste dierenarts, voor honden, katten en andere dieren die u opgeeft." },
      { q: "Handelt het herhaalmedicatie en voer af?", a: "Het neemt verzoeken aan, controleert het dossier van het dier en legt ze ter goedkeuring bij uw team, en vertelt de eigenaar wanneer het klaarstaat." },
      { q: "Neemt het buiten openingstijden op?", a: "Ja. Routinevragen en afspraken worden de hele nacht afgehandeld, en noodgevallen worden volgens uw protocol doorgeschakeld." },
      { q: "Stuurt het herinneringen?", a: "Ja. Vaccinatie- en controleherinneringen per telefoon of sms, en het plant meteen in als de eigenaar ja zegt." },
      { q: "Kent het onze dierenartsen en hun roosters?", a: "Ja. Het leest uw agenda en plant elke dierenarts volgens eigen tijden en regels." },
    ] },
  },
  de: {
    "/product": { title: T.de, items: [
      { q: "Was macht Optavius?", a: "Optavius nimmt das Telefon Ihrer Praxis mit einem KI-Sprachagenten entgegen. Er beantwortet Fragen, bucht, verschiebt und storniert Termine, gibt den Bestellstatus durch und leitet dringende Symptome nach Ihrem Protokoll weiter. Derselbe Agent bearbeitet auch Webchat, E-Mail, SMS und WhatsApp." },
      { q: "Ersetzt er unsere Rezeption?", a: "Nein. Er übernimmt die Routineanrufe, damit Ihr Team Zeit für den Patienten am Empfang hat. Alles Klinische, Dringende oder Ungewöhnliche geht an eine Person, mit dem Transkript." },
      { q: "Welche Sprachen spricht er?", a: "Deutsch, Englisch und Niederländisch, mit Klang und Formulierung der Region. Anrufer können mitten im Gespräch die Sprache wechseln." },
      { q: "Was passiert bei einem dringenden Symptom?", a: "Der Agent folgt der Warnsymptomliste, die Ihre klinisch verantwortliche Person freigegeben hat. Er sagt dem Anrufer, was zu tun ist, leitet an die Bereitschaftsnummer weiter, wenn das die Regel ist, und schickt Ihrem Team innerhalb von Sekunden eine Zusammenfassung." },
      { q: "Wie schnell sind wir live?", a: "Die meisten Praxen innerhalb von 48 Stunden. Sie leiten Ihre Nummer um, geben die Abläufe frei und sehen noch in derselben Woche die ersten Anrufe in der Konsole." },
      { q: "Woher wissen wir, dass er gute Arbeit macht?", a: "Jeder Anruf wird mit Transkript und Ergebnis protokolliert. Ein überwachender Agent bewertet eine Stichprobe auf Richtigkeit und Ton, und Sie sehen die Bewertungen in der Konsole." },
    ] },
    "/product/console": { title: T.de, items: [
      { q: "Was ist die Konsole?", a: "Der Ort, an dem Sie alles sehen, was die Agenten tun: jeden Anruf, jede Buchung und Weiterleitung, ein Morgenbriefing und eine Leiste, in der Sie Regeln in normaler Sprache ändern." },
      { q: "Was steht im Morgenbriefing?", a: "Anrufe der Nacht, gebuchte Termine, Weiterleitungen, alles Auffällige und was heute Ihre Entscheidung braucht. Jeden Morgen für Sie geschrieben." },
      { q: "Kann ich einen Agenten pausieren?", a: "Ja, mit einem Klick, pro Agent und pro Standort. Anrufe gehen dann an Ihr Team, bis Sie ihn wieder einschalten." },
      { q: "Wer kann die Konsole nutzen?", a: "Unbegrenzt viele Nutzer. Sie legen fest, wer was sieht, pro Standort und pro Rolle. Jede Änderung wird mit der Person protokolliert, die sie gemacht hat." },
      { q: "Gibt es eine App?", a: "Ja. Dieselbe Konsole als App, mit Push-Benachrichtigungen für Freigaben und das Morgenbriefing." },
      { q: "Kann ich eine Regel ändern, ohne Sie anzurufen?", a: "Ja. Tippen Sie es in die Befehlsleiste, zum Beispiel \"Dr. Alvarez freitags nicht mehr buchen\". Die Änderung erhält eine Referenz und lässt sich rückgängig machen." },
    ] },
    "/product/ask-optavius": { title: T.de, items: [
      { q: "Womit verbindet sich Ask Optavius?", a: "Mit Ihrem Kalender, Telefonsystem, dem Export aus dem Praxissystem und dem Überweisungspostfach, nur lesend. Standardanbindungen dauern einen Tag." },
      { q: "Ist es wirklich kostenlos?", a: "Ja, 90 Tage lang. Danach ist es bei jedem aktiven Agenten enthalten. Zum Start ist keine Karte nötig." },
      { q: "Kann es etwas in unseren Systemen ändern?", a: "Nein. Ask Optavius schreibt nie in Ihre Systeme. Es liest, antwortet und berichtet." },
      { q: "Welche Fragen kann ich stellen?", a: "Alles über Ihre eigene Praxis: No-Shows pro Standort, unbeantwortete Anrufe letzte Woche, Überweisungsrückstand, gebuchter Umsatz im nächsten Monat. Jede Antwort nennt das System und den Synchronisationszeitpunkt." },
      { q: "Wo liegen unsere Daten?", a: "In der Region Ihrer Praxis: in der EU für europäische Praxen, in den USA für amerikanische. Verschlüsselt bei der Übertragung und im Ruhezustand." },
      { q: "Was passiert nach den 90 Tagen?", a: "Sie behalten es mit jedem aktiven Agenten, oder die Verbindung wird geschlossen und die Daten innerhalb von 30 Tagen gelöscht." },
    ] },
    "/product/agents": { title: T.de, items: [
      { q: "Was ist ein Agent?", a: "Eine Aufgabe, von Anfang bis Ende erledigt. Der Empfangsagent nimmt an und bucht. Der Recall-Agent findet fällige Patienten und ruft an, bis sie gebucht sind. Jeder berichtet Ihnen täglich." },
      { q: "Welche Agenten kann ich einsetzen?", a: "Empfang, Terminbuchung, Bestellstatus, Recall und Erinnerungen, No-Show-Rückgewinnung, Warteliste, Überweisungsaufnahme, Aufnahme und Formulare, Webchat und E-Mail, Nachsorge nach Eingriffen, Bestellprüfung und Patientenabrechnung." },
      { q: "Was ist der Schattenmodus?", a: "Eine Woche mit echten Anrufen, ohne zu handeln. Sie sehen alles, was der Agent gesagt und getan hätte, bewertet vom Reviewer, bevor Sie ihn einschalten." },
      { q: "Wie füge ich einen Agenten hinzu?", a: "Mit einem Klick. Der Agent schlägt Regeln aus Ihren Praxisdaten vor, Sie passen sie in normaler Sprache an und geben frei. Die Abrechnung beginnt am Tag des Livegangs." },
      { q: "Arbeiten Agenten über mehrere Standorte?", a: "Ja. Ein Agent bedient mehrere Standorte mit eigenen Zeiten, Behandlern und Regeln, und Sie sehen jeden Standort einzeln in der Konsole." },
      { q: "Kann ich einen Agenten abschalten?", a: "Jederzeit, mit einem Klick. Anrufe gehen an Ihr Team, und nichts geht verloren." },
    ] },
    "/product/integrations": { title: T.de, items: [
      { q: "Muss ich mein Telefonsystem wechseln?", a: "Nein. Anrufe werden von jedem Telefonsystem an Optavius weitergeleitet: RingCentral, Zoom Phone, Twilio, Vonage, eine Telefonanlage oder ein SIP-Trunk. Ihre Nummer bleibt gleich." },
      { q: "Mit welchen Praxissystemen integrieren Sie?", a: "RevolutionEHR, Eyefinity, Crystal PM, Compulink, MaximEyes, ModMed, Nextech, Epic und ChipSoft per API oder FHIR, dazu Google Kalender, Outlook und Cal.com." },
      { q: "Können wir ohne Anbindung des Praxissystems starten?", a: "Ja. Die meisten Praxen starten nur mit dem Kalender und binden das Praxissystem später an. Termine werden dem Patienten so oder so per SMS bestätigt." },
      { q: "Wie kommen Buchungen in unser System?", a: "Synchronisation in beide Richtungen. Jede Buchung wird zurückgelesen, bevor sie dem Patienten bestätigt wird, also keine Doppelbuchungen und keine manuelle Eingabe." },
      { q: "Sind Patientendaten sicher?", a: "Datensätze sind FHIR-konform, mit AES-256 im Ruhezustand und TLS 1.3 bei der Übertragung verschlüsselt und in Ihrer Region gespeichert. Der Zugriff ist zunächst nur lesend; Schreibrechte werden pro Agent und pro Aktion vergeben." },
      { q: "Unser System steht nicht auf der Liste. Geht es trotzdem?", a: "Jedes System mit offener API oder MCP-Server lässt sich anbinden, abgegrenzt pro Praxis." },
    ] },
    "/specialties/ophthalmology": { title: T.de, items: [
      { q: "Wie geht der Agent mit Lichtblitzen, Mouches volantes oder plötzlichem Sehverlust um?", a: "Er folgt Ihrem Warnsymptomprotokoll: stellt die Fragen, die Ihre klinisch verantwortliche Person freigegeben hat, bietet einen Notfalltermin am selben Tag oder leitet an den Bereitschaftsdienst weiter und schickt Ihrem Team innerhalb von Sekunden eine Zusammenfassung." },
      { q: "Bucht er die richtige Terminart?", a: "Ja. Er unterscheidet eine Kataraktberatung von einer Injektion oder einer Nachkontrolle, bucht den richtigen Behandler und die richtige Dauer und bestätigt per SMS." },
      { q: "Bearbeitet er Überweisungen?", a: "Der Überweisungsagent liest jede Überweisung, prüft, was fehlt, fordert es an und ruft den Patienten zur Terminvereinbarung an. Nichts bleibt im Postfach liegen." },
      { q: "Kann er Patienten nach einer Operation anrufen?", a: "Ja. Der Nachsorgeagent ruft jeden operierten Patienten an, stellt Ihre Fragen und meldet Schmerzen, Rötung oder verschwommenes Sehen an Ihr Team." },
      { q: "Wir haben mehrere Standorte. Funktioniert das?", a: "Ja. Ein Agent deckt alle Standorte mit eigenen Zeiten und Behandlern ab, und Sie sehen jeden einzeln in der Konsole." },
      { q: "Gibt er medizinischen Rat?", a: "Nein. Er beantwortet, bucht, leitet weiter und eskaliert. Klinische Fragen gehen mit dem Transkript an Ihr Team." },
    ] },
    "/specialties/optometry": { title: T.de, items: [
      { q: "Kann er Kunden sagen, ob die Brille fertig ist?", a: "Ja. Er liest den Bestellstatus aus Ihrem System und sagt dem Anrufer, ob Brille, Gläser oder Bestellung fertig sind, sonst den voraussichtlichen Termin." },
      { q: "Bearbeitet er Kontaktlinsen-Nachbestellungen?", a: "Ja. Er prüft die Werte, bestätigt die Linsen und versendet an die hinterlegte Adresse, oder bucht eine Kontrolle, wenn die Werte abgelaufen sind." },
      { q: "Und Fragen zur Kostenübernahme?", a: "Er beantwortet, welche Kassen und Versicherungen Sie annehmen, was ein Sehtest kostet und was übernommen wird, nach den Skripten, die Sie freigeben." },
      { q: "Nimmt er außerhalb der Öffnungszeiten an?", a: "Ja, die ganze Nacht und das ganze Wochenende. Anrufer buchen, bestellen nach oder hinterlassen ein Anliegen, und Ihr Team findet es im Morgenbriefing." },
      { q: "Funktioniert er für eine Kette mit mehreren Filialen?", a: "Ja. Jede Filiale hat eigene Zeiten, Mitarbeiter und Kalender, und der Agent weiß, welche welche ist." },
      { q: "Klingt er wie unser Geschäft?", a: "Sie geben Begrüßung, Ton und Skripte frei. Er nennt Ihren Geschäftsnamen und folgt Ihren Regeln." },
    ] },
    "/specialties/dermatology": { title: T.de, items: [
      { q: "Wie geht er mit einem veränderten Muttermal oder plötzlichem Ausschlag um?", a: "Er stellt die Fragen Ihrer Liste dringender Hautbefunde, bietet einen Notfalltermin oder leitet nach Ihrem Protokoll weiter und schickt Ihrem Team eine Zusammenfassung." },
      { q: "Kann er medizinische und kosmetische Termine trennen?", a: "Ja. Er bucht für beide die richtige Terminart, den richtigen Behandler und die richtige Dauer und wendet Ihre Anzahlungs- oder Stornoregeln für kosmetische Termine an." },
      { q: "Bearbeitet er Rezeptanfragen?", a: "Er nimmt die Anfrage entgegen, prüft die Patientendaten und gibt sie zur Freigabe an Ihr Team. Er stellt selbst nie ein Rezept aus." },
      { q: "Kann er abgesagte Termine nachbesetzen?", a: "Ja. Wird ein Termin frei, arbeitet der Wartelistenagent Ihre Liste ab, bis er besetzt ist." },
      { q: "Und Hinweise vor dem Besuch?", a: "Er sendet Vorbereitungshinweise und Formulare per SMS oder E-Mail und bestätigt vor dem Besuch, dass der Patient bereit ist." },
      { q: "Erfüllt er die Regeln für Gesundheitsdaten?", a: "DSGVO in Europa, HIPAA in den USA, mit Daten in Ihrer Region und jedem Anruf protokolliert und prüfbar." },
    ] },
    "/specialties/veterinary": { title: T.de, items: [
      { q: "Was passiert, wenn ein Halter mit einem Notfall anruft?", a: "Der Agent folgt Ihrem Notfallprotokoll: sagt dem Halter, was jetzt zu tun ist, leitet an den diensthabenden Tierarzt oder die Notfallklinik weiter und schickt Ihrem Team eine Zusammenfassung." },
      { q: "Kann er verschiedene Terminarten buchen?", a: "Ja. Impfungen, Kontrollen, OP-Beratungen und Fellpflege, mit der richtigen Dauer und dem richtigen Tierarzt, für Hunde, Katzen und andere Tiere, die Sie angeben." },
      { q: "Bearbeitet er Medikamenten- und Futternachbestellungen?", a: "Er nimmt Anfragen entgegen, prüft die Akte des Tieres und gibt sie zur Freigabe an Ihr Team, dann sagt er dem Halter, wann es abholbereit ist." },
      { q: "Nimmt er außerhalb der Öffnungszeiten an?", a: "Ja. Routinefragen und Buchungen werden die ganze Nacht erledigt, Notfälle nach Ihrem Protokoll weitergeleitet." },
      { q: "Verschickt er Erinnerungen?", a: "Ja. Impf- und Kontrollerinnerungen per Anruf oder SMS, und er bucht sofort, wenn der Halter zusagt." },
      { q: "Kennt er unsere Tierärzte und ihre Dienstpläne?", a: "Ja. Er liest Ihren Kalender und bucht jeden Tierarzt nach eigenen Zeiten und Regeln." },
    ] },
  },
};
