// Original Horizon "moments" copy -> eye-care copy (applied to public/moments/*.json and the initial tab panels)
module.exports = {
  // ---- Tab 0: providers (eye clinic referral)
  'From referral to scheduled appointment': 'From eye exam referral to fitted lenses',
  'Horizon coordinates payers, providers, and patients until the follow-up is booked.': 'Horizon coordinates plans, clinics, and patients until the fitting is booked.',
  'Open cardiology referral with no appointment scheduled': 'Open ophthalmology referral with no eye exam scheduled',
  'Your cardiology referral is ready to schedule. I can help find a time that works.': 'Your ophthalmology referral is ready to schedule. I can help find a time for your eye exam.',
  'Finds available cardiology appointments': 'Finds available eye exam slots',
  'Reading the open referral': 'Reading the open eye exam referral',
  'Recalling phone opt-in': 'Recalling phone opt-in',
  'Calls the patient': 'Calls the patient',
  'Comparing outreach channels': 'Comparing outreach channels',
  'The patient has opted in to phone outreach.': 'The patient has opted in to phone outreach.',
  'Do you have any afternoon appointments?': 'Do you have any afternoon exam slots?',
  'I can offer Tuesday at 2:00 or Thursday at 3:30. Which works better?': 'I can offer Tuesday at 2:00 or Thursday at 3:30 with Dr. Okafor. Which works better?',
  'Thursday at 3:30 works.': 'Thursday at 3:30 works.',
  'Books the Thursday 3:30 appointment': 'Books the Thursday 3:30 eye exam',
  'Finds later afternoon appointments': 'Finds later afternoon exam slots',
  'Appointment scheduled': 'Eye exam scheduled',
  'Great! We’re looking forward to seeing you. Please fill out these intake forms before you come.': 'Great! We’re looking forward to seeing you. Please fill out your vision history form before you come.',
  'Need forms completed ahead of appointment, patient has not yet filled out.': 'Vision history form needed ahead of the exam; patient has not yet filled it out.',
  'Prior authorization was denied': 'Lens fitting authorization was denied',
  'Prior authorization denial requires payer follow-up': 'Fitting authorization denial requires vision plan follow-up',
  'New prior authorization denial': 'New lens fitting authorization denial',
  'Prior authorization approved': 'Lens fitting authorization approved',
  'Prior authorization is now approved': 'Lens fitting authorization is now approved',
  'Patient has appointment scheduled for tomorrow and needs prior auth to proceed. Patient prefers afternoons.': 'Patient has a lens fitting scheduled for tomorrow and needs plan authorization to proceed. Patient prefers afternoons.',
  'Your appointment is tomorrow, but the prior authorization was denied. I need to move the visit while we resolve it. Does next week work?': 'Your fitting is tomorrow, but the plan authorization was denied. I need to move the visit while we resolve it. Does next week work?',
  'Your appointment is tomorrow, but the prior authorization was denied. I need to move the visit while we resolv': 'Your fitting is tomorrow, but the plan authorization was denied. I need to move the visit while we resolv',
  'Determining that rescheduling is safer than holding the visit': 'Determining that rescheduling is safer than holding the fitting',
  'Calls the patient to reschedule appointment': 'Calls the patient to reschedule the fitting',
  'Okay. Do you have an afternoon next week?': 'Okay. Do you have an afternoon next week?',
  'Next Tuesday at 12pm is available. Would you like me to book it?': 'Next Tuesday at 12pm is available. Would you like me to book it?',
  'Confirms next Tuesday at 12pm': 'Confirms next Tuesday at 12pm',
  'I’m calling about the denied authorization. Can you tell me why it was denied?': 'I’m calling about the denied lens authorization. Can you tell me why it was denied?',
  'Calls payer for denial reason': 'Calls the vision plan for the denial reason',
  'Denial reason is not documented': 'Denial reason is not documented',
  'The request is missing updated clinical notes from the referring provider.': 'The request is missing the updated prescription from the referring optometrist.',
  'Thank you. I’ll send that requirement to the provider now.': 'Thank you. I’ll send that requirement to the optometrist now.',
  'Identifies that updated clinical notes are required': 'Identifies that an updated prescription is required',
  'Sends the denial reason and clinical-notes request': 'Sends the denial reason and prescription request',
  'Matching missing requirement to right provider': 'Matching missing requirement to the right optometrist',
  'The denied authorization needs to be confirmed ahead of the Tuesday appointment.': 'The denied authorization needs to be confirmed ahead of the Tuesday fitting.',
  'Good news — your prior authorization was approved. You’re still scheduled for next Tuesday at 12pm. Does that still work?': 'Good news — your lens fitting was approved. You’re still scheduled for next Tuesday at 12pm. Does that still work?',
  'Good news — your prior authorization was approved. You’re still scheduled for next Tuesday at 12pm. Does that ': 'Good news — your lens fitting was approved. You’re still scheduled for next Tuesday at 12pm. Does that ',
  'Verifies next Tuesday at 12pm remains booked': 'Verifies next Tuesday at 12pm remains booked',
  'Confirms the existing rescheduled appointment with the patient': 'Confirms the rescheduled fitting with the patient',
  'Confirms the upcoming appointment': 'Confirms the upcoming fitting',
  'Recalling the rescheduled appointment and the patient’s SMS preference': 'Recalling the rescheduled fitting and the patient’s SMS preference',
  'Yes, I’ll be there.': 'Yes, I’ll be there.',
  'Provider messaging': 'Clinic messaging',
  'Payer': 'Vision plan',
  'EHR': 'Practice EHR',
  'Comparing resolution paths': 'Comparing resolution paths',
  'For providers': 'For eye clinics',
  // ---- Tab 1: insurers (broken glasses claim)
  'From FNOL to claim resolution': 'From broken glasses to reimbursed',
  'Horizon orchestrates every stage of the claims lifecycle, from FNOL to inspections, repairs, rentals, and resolution.': 'Horizon orchestrates every stage of a lens claim, from first notice to assessment, replacements, loaners, and payout.',
  'Horizon orchestrates every stage of the claims lifecycle, from FNOL to inspections, repairs, rentals, and reso': 'Horizon orchestrates every stage of a lens claim, from first notice to assessment, replacements, loaners, and ',
  'Claim is created': 'Vision claim is created',
  'Your claim has been created. Can you send photos of the damage and any police report?': 'Your claim has been created. Can you send photos of the damaged glasses and your proof of purchase?',
  'Here are photos, no police report yet.': 'Here are photos, no receipt yet.',
  'Got them. I\'ll follow up on the police report so nothing stalls.': 'Got them. I\'ll follow up on the receipt so nothing stalls.',
  'Claim opened — evidence requested, police report pending': 'Claim opened — photos received, receipt pending',
  'Logs the pending police report follow-up': 'Logs the pending receipt follow-up',
  'Reading new claim in claims system': 'Reading the new claim in the vision plan system',
  'Pulls prior-claim and loss history to flag gaps': 'Pulls prior claims and lens history to flag gaps',
  'Choosing evidence follow-up playbook': 'Choosing the evidence follow-up playbook',
  'Runs the evidence follow-up playbook to capture complete loss details and evidence': 'Runs the evidence playbook to capture how the glasses broke and the proof of purchase',
  'Checking missing loss and evidence details': 'Checking missing damage and evidence details',
  'Confirms the claim has been created and requests photos and any police report': 'Confirms the claim has been created and requests photos and the receipt',
  'The policy, loss details, initial loss classification, and evidence submitted so far stay connected.': 'The vision plan, damage details, the lens prescription, and evidence submitted so far stay connected.',
  'Evidence is in, coverage and liability need validation': 'Evidence is in, coverage and eligibility need validation',
  'Good news, your coverage has been confirmed. I can help schedule your repair at a nearby approved shop.': 'Good news, your coverage has been confirmed. I can book a lens replacement at a nearby partner optician.',
  'Great. Anything I should do to prepare for the appointment?': 'Great. Anything I should do to prepare for the appointment?',
  'Confirms coverage, limits, and deductible against the policy': 'Confirms coverage, frame allowance, and copay against the plan',
  'Verifying whether stated damage is covered': 'Verifying whether the damage is covered',
  'Weighing prior-claim history for red flags': 'Weighing prior claims for red flags',
  'Validates coverage and chases only the details that are actually missing': 'Validates coverage and chases only the details that are actually missing',
  'Coverage confirmed — estimate in, moving to coordination': 'Coverage confirmed — lens estimate in, moving to coordination',
  'Inspection, repair, and rental to coordinate': 'Assessment, replacement lenses, and loaner glasses to coordinate',
  'Inspection, repair, and rental booked and in sync': 'Assessment, lens replacement, and loaner glasses booked and in sync',
  'Your inspection and repair are scheduled for Thursday. Would you like a rental while your vehicle is being repaired?': 'Your assessment and lens replacement are scheduled for Thursday. Would you like loaner glasses while yours are being made?',
  'Your inspection and repair are scheduled for Thursday. Would you like a rental while your vehicle is being rep': 'Your assessment and lens replacement are scheduled for Thursday. Would you like loaner glasses while yours are',
  'Yes please, I need a car.': 'Yes please, I can’t read without them.',
  'Done — Great. Your rental is confirmed for Thursday and covered for the scheduled repair period.': 'Done — your loaner glasses are ready for pickup Thursday and covered until your lenses arrive.',
  'Books the inspection and assigns an approved repair shop': 'Books the assessment and assigns a partner optician',
  'Sets up a covered rental for the repair window': 'Arranges covered loaner glasses for the replacement window',
  'Checking rental eligibility for repair window': 'Checking loaner eligibility for the replacement window',
  'Coordinates the inspection, repair shop, and rental across third parties': 'Coordinates the assessment, lens lab, and loaner glasses across partners',
  'Sequencing inspection, repair, and rental': 'Sequencing assessment, lens replacement, and loaners',
  'Recalling approved scope and preferred vendors': 'Recalling approved scope and preferred opticians',
  'The approved scope, preferred vendors, and rental eligibility stay connected.': 'The approved scope, partner opticians, and loaner eligibility stay connected.',
  'The policy terms, deductible, and prior-claim history stay connected.': 'The plan terms, copay, and prior-claim history stay connected.',
  'Repairs complete and settlement decision ready': 'Lenses fitted and reimbursement decision ready',
  'Your claim has been settled for $4,200 after your deductible. Would you prefer direct deposit or a check?': 'Your claim has been settled for $420 after your copay. Would you prefer direct deposit or a check?',
  'Direct deposit, thanks.': 'Direct deposit, thanks.',
  'Communicates the settlement decision and coordinates payment': 'Communicates the reimbursement decision and coordinates payment',
  'Routes the decision for human sign-off before it goes out': 'Routes the decision for human sign-off before it goes out',
  'Routing decision for adjuster sign-off': 'Routing decision for claims-reviewer sign-off',
  'Adjuster review': 'Claims reviewer',
  'Confirming payment method': 'Confirming payment method',
  'Calculating payment': 'Calculating reimbursement',
  'Claim resolved': 'Claim reimbursed',
  'Settlement paid — $4,200 via direct deposit': 'Reimbursement paid — $420 via direct deposit',
  'Issues payment to the policyholder\'s chosen method': 'Issues payment to the member\'s chosen method',
  'Your payment has been issued. It should arrive within 1–2 business days, and I\'ve emailed you the settlement breakdown.': 'Your reimbursement has been issued. It should arrive within 1–2 business days, and I\'ve emailed you the breakdown.',
  'Your payment has been issued. It should arrive within 1–2 business days, and I\'ve emailed you the settlement b': 'Your reimbursement has been issued. It should arrive within 1–2 business days, and I\'ve emailed you the break',
  'The approved amount, deductible, and payment method stay connected.': 'The approved amount, copay, and payment method stay connected.',
  'You\'re all set! Just bring your keys and remove any personal belongings. We\'ll be in touch soon with next steps.': 'You\'re all set! Just bring your broken glasses and your current prescription. We\'ll be in touch soon with next steps.',
  'You\'re all set! Just bring your keys and remove any personal belongings. We\'ll be in touch soon with next step': 'You\'re all set! Just bring your broken glasses and your current prescription. We\'ll be in touch with next step',
  'Guidewire, Duck Creek & more': 'Vision plan platforms & more',
  'Claims system': 'Vision claims system',
  'Claims information exchange': 'Optician network exchange',
  'Policy check': 'Plan check',
  'Policyholder': 'Plan member',
  'Rental': 'Loaner glasses',
  'For insurers': 'For vision plans',
  // ---- Tab 2: carriers (lens subscription at risk)
  'From churn risk to renewed subscriber': 'From churn risk to renewed lens plan',
  'Horizon catches the churn signal, audits the bill behind it, and locks in loyalty with the right offer.': 'Horizon catches the churn signal, audits the lens bill behind it, and locks in loyalty with the right offer.',
  'Bill too high, considering a competitor': 'Lens bill too high, considering an online store',
  'Inbound message — bill too high, considering a competitor': 'Inbound message — lens bill too high, considering an online store',
  'My bill\'s way up this month. A competitor quoted me less and I\'m thinking of switching.': 'My lens bill\'s way up this month. An online store quoted me less and I\'m thinking of switching.',
  'Let me find out what changed': 'Let me find out what changed',
  'Reading the cancel threat and competitor quote': 'Reading the cancel threat and the online quote',
  'Recalling three years, two lines, on autopay': 'Recalling three years, two wearers, on autopay',
  'Three years on the same plan, two lines, enrolled in autopay.': 'Three years on the same lens plan, two wearers, enrolled in autopay.',
  'Treats the cancel threat as a case to solve, not a ticket to route': 'Treats the cancel threat as a case to solve, not a ticket to route',
  'Choosing to solve the bill, not route the ticket': 'Choosing to solve the bill, not route the ticket',
  'Records the competitor quote as an active churn signal': 'Records the online quote as an active churn signal',
  'Cancel intent captured, case opened': 'Cancel intent captured, case opened',
  'Cancel case opened — churn signal logged': 'Cancel case opened — churn signal logged',
  'Scoring churn risk as high, and the lifetime value worth saving': 'Scoring churn risk as high, and the lifetime value worth saving',
  'Conduct bill audit': 'Conduct lens bill audit',
  'Pulls the invoices and payment history': 'Pulls the lens invoices and payment history',
  'Pulling this cycle against the last three': 'Pulling this cycle against the last three',
  'Spotting the one missed autopay last cycle': 'Spotting the one missed autopay last cycle',
  'Finds one root cause — the failed autopay triggered a late fee and dropped the autopay discount': 'Finds one root cause — the failed autopay triggered a late fee and dropped the subscribe-and-save discount',
  'Tracing the late fee to that missed payment': 'Tracing the late fee to that missed payment',
  'Linking the lost autopay discount to it': 'Linking the lost subscribe-and-save discount to it',
  'Autopay failed once last cycle — payment history otherwise spotless for three years.': 'Autopay failed once last cycle — payment history otherwise spotless for three years.',
  'Diagnosis': 'Diagnosis',
  'Case #B-2214 — one missed autopay caused a late fee and removed the discount. First miss in three years. Please waive the fee and reinstate the discount.': 'Case #L-2214 — one missed autopay caused a late fee and removed the lens discount. First miss in three years. Please waive the fee and reinstate the discount.',
  'Case #B-2214 — one missed autopay caused a late fee and removed the discount. First miss in three years. Pleas': 'Case #L-2214 — one missed autopay caused a late fee and removed the lens discount. First miss in three years. ',
  'Deciding to request the waiver and reinstatement': 'Deciding to request the waiver and reinstatement',
  'Approved — fee waived, discount restored this cycle.': 'Approved — fee waived, lens discount restored this cycle.',
  'Fee waived, discount restored': 'Fee waived, lens discount restored',
  'Late fee waived, autopay discount restored': 'Late fee waived, lens discount restored',
  'Good news — the late fee has been waived and your autopay discount is restored. Your next bill will be back to normal.': 'Good news — the late fee has been waived and your lens discount is restored. Your next bill will be back to normal.',
  'Good news — the late fee has been waived and your autopay discount is restored. Your next bill will be back to': 'Good news — the late fee has been waived and your lens discount is restored. Your next bill will be back to',
  'Choosing to share the fix before they ask': 'Choosing to share the fix before they ask',
  'Confirming the credit posted and discount restored': 'Confirming the credit posted and discount restored',
  'Bill resolved, risk re-checked': 'Bill resolved, risk re-checked',
  'Bill resolved — churn re-scored, contract-end flagged': 'Bill resolved — churn re-scored, plan renewal flagged',
  'Closes the loop — and re-runs the churn check': 'Closes the loop — and re-runs the churn check',
  'Deciding to re-run the churn check': 'Deciding to re-run the churn check',
  'Re-scores the risk — improved, but the contract ends in 30 days': 'Re-scores the risk — improved, but the lens plan ends in 30 days',
  'Churn re-scored, contract-end flagged': 'Churn re-scored, plan renewal flagged',
  'Contract ends in 30 days': 'Lens plan ends in 30 days',
  'Reading the contract-end date, 30 days out': 'Reading the plan renewal date, 30 days out',
  'Recalling the competitor quote still on file': 'Recalling the online quote still on file',
  'The competitor quote is still on file.': 'The online quote is still on file.',
  'Weighing the tenure against the quote on file': 'Weighing the tenure against the quote on file',
  'Choosing to preempt before they shop again': 'Choosing to preempt before they shop again',
  'Preempts the contract-end risk with a loyalty offer': 'Preempts the renewal risk with a loyalty lens price',
  'One more thing — your contract\'s up next month. After three years with us, you qualify for a loyalty rate. Want me to lock it in?': 'One more thing — your lens plan renews next month. After three years with us, you qualify for a loyalty price. Want me to lock it in?',
  'One more thing — your contract\'s up next month. After three years with us, you qualify for a loyalty rate. Wan': 'One more thing — your lens plan renews next month. After three years with us, you qualify for a loyalty price.',
  'That\'s better than the other prices I\'m seeing. Let\'s do it.': 'That\'s better than the online prices I\'m seeing. Let\'s do it.',
  'Applies the loyalty rate and renews the line': 'Applies the loyalty price and renews the lens plan',
  'Confirming loyalty rate B is approved': 'Confirming loyalty price B is approved',
  'Renewed at loyalty rate — line locked for the year': 'Renewed at loyalty price — lens plan locked for the year',
  'Subscriber saved — renewed at a loyalty rate': 'Subscriber saved — renewed at a loyalty price',
  'Billing & CRM': 'Billing & CRM',
  'Churn Model & CDP': 'Churn Model & CDP',
  'Churn model': 'Churn model',
  'For carriers': 'For lens subscriptions',
  // ---- Tab 3: media (free trial -> family plan) => eye-care app trial -> family vision plan
  'From free trial to family plan': 'From free trial to family vision plan',
  'Horizon guides each viewer to the right plan, so trials convert and stick.': 'Horizon guides each member to the right vision plan, so trials convert and stick.',
  'Trial ends in 72 hours, no card': 'Trial ends in 72 hours, no card',
  'Trial ends in 72 hours, no card on file': 'Trial ends in 72 hours, no card on file',
  'A full evening of viewing last night, trial ends at midnight': 'A full eye-strain check last night, trial ends at midnight',
  'You\'re two episodes from the Wilderness finale, and your free trial ends Thursday. Want to keep watching?': 'You\'re two days from finishing the 14-day blue-light lens trial, and it ends Thursday. Want to keep them?',
  'Maybe. Does my watchlist carry over if I sign up?': 'Maybe. Does my saved frames list carry over if I sign up?',
  'Everything carries over: watchlist, profiles, and where you left off.': 'Everything carries over: saved frames, family profiles, and your prescriptions.',
  'Not yet. I want to see what else is on first.': 'Not yet. I want to compare a few frames first.',
  'Take your time. I\'ll check back tomorrow with a few picks.': 'Take your time. I\'ll check back tomorrow with a few frame picks.',
  'Reading latest viewing': 'Reading latest wear data',
  'Reading watch history': 'Reading wear history',
  'Judging the moment is right': 'Judging the moment is right',
  'Opens with the finale household hasn\'t finished': 'Opens with the trial the household hasn\'t finished',
  'Logs watchlist question as buying intent': 'Logs saved-frames question as buying intent',
  'Notes the pause and schedules tomorrow\'s follow-up': 'Notes the pause and schedules tomorrow\'s follow-up',
  'Interest surfaced — watchlist carryover confirmed': 'Interest surfaced — saved frames carryover confirmed',
  'Watchlist-carryover question': 'Saved-frames carryover question',
  'Knows they asked yesterday whether the watchlist carries over.': 'Knows they asked yesterday whether saved frames carry over.',
  'Carries yesterday\'s pause and the plan they were considering.': 'Carries yesterday\'s pause and the plan they were considering.',
  'Carrying pause and plan': 'Carrying pause and plan',
  'Buying intent logged — watchlist carryover asked': 'Buying intent logged — saved-frames carryover asked',
  'Four devices, three profiles, viewing every night of the trial': 'Two adults, two kids, lenses worn every day of the trial',
  'Weekly family viewing across all three profiles': 'Weekly wear across all four family profiles',
  'Reading devices and profiles from CDP': 'Reading family profiles from CDP',
  'Matching household to plan': 'Matching household to plan',
  'Choosing fit over biggest plan': 'Choosing fit over biggest plan',
  'Based on how your family watched this month, the 4-screen family plan fits best. Want me to set it up?': 'Based on how your family wore their lenses this month, the 4-member family vision plan fits best. Want me to set it up?',
  'Yeah ok, let\'s do the 4-screen plan.': 'Yeah ok, let\'s do the family plan.',
  'Here\'s the payment link. First charge tomorrow, renews monthly, cancel anytime.': 'Here\'s the payment link. First charge tomorrow, renews monthly, cancel anytime.',
  'Paid.': 'Paid.',
  'Starts the family plan, first charge after the trial ends': 'Starts the family vision plan, first charge after the trial ends',
  'Follows up with picks, then completes the signup in the same thread': 'Follows up with frame picks, then completes the signup in the same thread',
  'Plan recommended — follow-up set for tomorrow': 'Plan recommended — follow-up set for tomorrow',
  'Trials converted': 'Trials converted',
  'One household subscribed and engaged': 'One household enrolled and engaged',
  'Picking a next watch': 'Picking a next frame',
  'Steady weekly viewing': 'Steady weekly wear',
  'Spotting premiere to flag': 'Spotting the new collection to flag',
  'Choosing content over a discount': 'Choosing a new collection over a discount',
  'Holds the Friday movie-night habit and the reminder it promised at signup.': 'Holds the Friday try-on habit and the reminder it promised at signup.',
  'If you loved Wilderness, Star Rangers is a family favorite. Your trial ends tonight. Any other questions before it does?': 'If you loved the blue-light lenses, the anti-glare pair is a family favorite. Your trial ends tonight. Any other questions before it does?',
  'If you loved Wilderness, Star Rangers is a family favorite. Your trial ends tonight. Any other questions befor': 'If you loved the blue-light lenses, the anti-glare pair is a family favorite. Your trial ends tonight. Any que',
  'Good to know.': 'Good to know.',
  'Welcome. I\'ll shoot you a reminder when Wilderness Season 2 premieres next month.': 'Welcome. I\'ll shoot you a reminder when the new spring collection lands next month.',
  'Wilderness Season 2 is finally out. Want it queued up for Friday movie night?': 'The spring frame collection is finally out. Want a Friday try-on booked for the family?',
  'Yes please.': 'Yes please.',
  'Tracks the new subscriber through day 30 and messages only when there\'s a reason': 'Tracks the new member through day 30 and messages only when there\'s a reason',
  'Records the household as active and retained at day 30': 'Records the household as active and retained at day 30',
  'Active at day 30 — new-season nudge sent': 'Active at day 30 — new-collection nudge sent',
  'Family plan started — Season 2 reminder promised': 'Family plan started — collection reminder promised',
  'Identified reason to reach out': 'Identified reason to reach out',
  'Billing, CDP & content systems': 'Billing, CDP & inventory systems',
  'Data platform': 'Data platform',
  'In-app chat': 'In-app chat',
  'Viewer': 'Member',
  'Subscriber': 'Member',
  'For media brands': 'For eye-care memberships',
  'Last day': 'Last day',
  // ---- Tab 4: travel (booked -> upgraded) => standard exam booked -> premium lenses
  'From booked to upgraded': 'From booked exam to premium lenses',
  'Horizon works the pre-trip window for the right upgrades and ancillaries.': 'Horizon works the pre-visit window for the right lens upgrades and add-ons.',
  'Traveler has a departure in two weeks': 'Patient has an eye exam in two weeks',
  'New booking in economy': 'New booking for a standard exam',
  'Reading the new economy booking in Reservations': 'Reading the new standard exam booking in Scheduling',
  'Reading flight history, card status, and loyalty tier': 'Reading exam history, plan status, and loyalty tier',
  'The last 12 months of flying, card status, and loyalty tier.': 'The last 12 months of visits, plan status, and loyalty tier.',
  'Starts watching the trip — and opens a conversation to learn what to watch for': 'Starts watching the visit — and opens a conversation to learn what to watch for',
  'Decision to monitor the flight for cabin upgrade opportunities': 'Decision to monitor the visit for lens upgrade opportunities',
  'You\'re booked for Thursday the 12th! Want me to keep an eye out if a better seat opens up?': 'You\'re booked for Thursday the 12th! Want me to keep an eye out if a premium lens slot opens up?',
  'Yes — business if it\'s reasonable. And I prefer aisle.': 'Yes — progressives if it\'s reasonable. And I prefer thin lenses.',
  'Noted — I\'ll watch your flight and reach out the moment something opens.': 'Noted — I\'ll watch your visit and reach out the moment something opens.',
  'Saves the seat preferences and sets a seat watch': 'Saves the lens preferences and sets a slot watch',
  'Booking watched — seat preferences saved (business, aisle)': 'Booking watched — lens preferences saved (progressive, thin)',
  'The booking, loyalty profile, and stated preferences.': 'The booking, loyalty profile, and stated preferences.',
  'State preferences and miles balance.': 'Stated preferences and points balance.',
  'Outbound SMS right after booking': 'Outbound SMS right after booking',
  'Outbound SMS ahead of the trip': 'Outbound SMS ahead of the visit',
  'Weighing offers — cabin upgrade, loyalty membership, credit card, or flight protection': 'Weighing offers — lens upgrade, loyalty membership, vision plan card, or lens protection',
  'Scores next-best offers by likelihood to convert': 'Scores next-best offers by likelihood to convert',
  'Scoring the co-brand card as most likely to convert': 'Scoring the vision plan card as most likely to convert',
  'Sierra Intelligence picks the offer most likely to convert — here, the co-brand card': 'Sierra Intelligence picks the offer most likely to convert — here, the vision plan card',
  'Making a judgment about the highest value upgrade offer': 'Making a judgment about the highest value upgrade offer',
  'Based on your last 12 months of flying, the co-brand card would have earned you ~28,000 miles.': 'Based on your last 12 months of visits, the vision plan card would have earned you ~28,000 points.',
  'Fee vs. benefits? Break it down for me.': 'Fee vs. benefits? Break it down for me.',
  '$95 vs. free bags + ~28k miles a year. I can start the application now — just tell me when.': '$95 vs. free lens cleanings + ~28k points a year. I can start the application now — just tell me when.',
  'Yeah, please go ahead.': 'Yeah, please go ahead.',
  'Card application started': 'Plan card application started',
  'Co-brand card application started': 'Vision plan card application started',
  'Recalling traveler priorities': 'Recalling patient priorities',
  'Cancellation frees a business class seat on their flight': 'A cancellation frees a premium lens fitting slot on their visit day',
  'Observing an available business seat in the PSS': 'Observing an available fitting slot in Scheduling',
  'Matches the freed seat to the preference they stated at booking — and reaches out': 'Matches the freed slot to the preference they stated at booking — and reaches out',
  'Matching it to the business cabin, aisle seat wanted': 'Matching it to the progressive, thin lenses wanted',
  'Checking if available miles covers fare': 'Checking if available points cover the upgrade',
  'Checks the miles balance covers the fare': 'Checks the points balance covers the upgrade',
  'Reaching out before the seat\'s gone': 'Reaching out before the slot\'s gone',
  'Outbound SMS when the seat opens': 'Outbound SMS when the slot opens',
  'That business seat you asked about just opened — your 41,000 miles more than cover it.': 'That progressive lens fitting you asked about just opened — your 41,000 points more than cover it.',
  'In a meeting — can you call me tonight instead?': 'In a meeting — can you call me tonight instead?',
  'Of course — I\'ll call you at 7pm.': 'Of course — I\'ll call you at 7pm.',
  'Business seat matched — 7pm call-back promised': 'Premium fitting matched — 7pm call-back promised',
  'Call-back traveler asked for': 'Call-back the patient asked for',
  'The call-back time the traveler asked for arrives': 'The call-back time the patient asked for arrives',
  'Outbound call at the agreed time': 'Outbound call at the agreed time',
  'Resuming thread to close upgrade': 'Resuming thread to close the upgrade',
  'Picks the conversation back up right where it left off — and closes the upgrade': 'Picks the conversation back up right where it left off — and closes the upgrade',
  'Calling as promised — still want that business seat? It\'s 25,000 miles, aisle 3C.': 'Calling as promised — still want those progressive lenses? It\'s 25,000 points, thin-lens option.',
  'Yes — book it.': 'Yes — book it.',
  'Done — you\'re in 3C. Your new boarding pass is in your wallet.': 'Done — you\'re booked for the fitting. Your updated lens order is in your app.',
  'Books seat 3C and issues the new boarding pass': 'Books the fitting and issues the updated lens order',
  'The available seat, the miles math, and the promised time.': 'The available slot, the points math, and the promised time.',
  'Upgrade booked': 'Lens upgrade booked',
  'Upgrade booked — seat 3C, boarding pass issued': 'Lens upgrade booked — progressive fitting, order issued',
  'Inventory / PSS': 'Inventory / Scheduling',
  'Reservations': 'Scheduling',
  'PSS': 'Scheduling',
  'Traveler': 'Patient',
  'Loyalty': 'Loyalty',
  'Call': 'Call',
  'For travel brands': 'For optical retailers',
  // ---- Tab 5: consumer services (missed booking -> repeat customer) => mobile optician home visit
  'From missed booking to repeat customer': 'From missed fitting to repeat customer',
  'Horizon recovers the missed booking and sees the job through to the next one.': 'Horizon recovers the missed fitting and sees the visit through to the next one.',
  'Customer didn\'t finish booking a service': 'Customer didn\'t finish booking a home eye test',
  'Abandoned booking, service needed': 'Abandoned booking, eye test needed',
  'Recalling abandoned booking details': 'Recalling abandoned booking details',
  'Runs lead follow-up before booking is lost': 'Runs lead follow-up before the booking is lost',
  'You didn\'t finish booking your service — still want to? I can take 10% off to lock it in.': 'You didn\'t finish booking your home eye test — still want to? I can take 10% off to lock it in.',
  'Yeah, let\'s do it.': 'Yeah, let\'s do it.',
  'Weighing incentive': 'Weighing incentive',
  'Determining right recovery': 'Determining the right recovery',
  'Choosing channel to re-engage': 'Choosing channel to re-engage',
  'Initiates outbound call or SMS': 'Initiates outbound call or SMS',
  'Call or SMS': 'Call or SMS',
  'Customer has an upcoming booking': 'Customer has an upcoming eye test',
  'Runs booking confirmation ahead of appointment': 'Runs booking confirmation ahead of the visit',
  'Reminder — your service is booked for tomorrow at 10am. Does that time still work?': 'Reminder — your home eye test is booked for tomorrow at 10am. Does that time still work?',
  'Actually, can we move it to Friday?': 'Actually, can we move it to Friday?',
  'No problem — moved to Friday at 10am. See you then!': 'No problem — moved to Friday at 10am. See you then!',
  'Confirming time': 'Confirming time',
  'Appointment moved to Friday 10am': 'Eye test moved to Friday 10am',
  'Booking confirmed — Thursday 10am': 'Eye test confirmed — Thursday 10am',
  'Recalling upcoming appointment': 'Recalling the upcoming eye test',
  'The appointment time, service details, reschedule policy': 'The visit time, test details, reschedule policy',
  'Customer is waiting for service': 'Customer is waiting for the optician',
  'Identifying technician\'s location': 'Identifying the optician\'s location',
  'Estimating arrival window': 'Estimating arrival window',
  'Keeps customer informed with live ETAs': 'Keeps the customer informed with live ETAs',
  'Providing real-time updates': 'Providing real-time updates',
  'Your technician\'s on the way — ETA about 20 minutes.': 'Your optician\'s on the way — ETA about 20 minutes.',
  'Great, thanks for the heads up!': 'Great, thanks for the heads up!',
  'Service in progress — ETA shared': 'Visit in progress — ETA shared',
  'The technician location, job status': 'The optician location, visit status',
  'Customer received service': 'Customer received the eye test',
  'Runs post-service follow-up — rate, recover, and rebook': 'Runs post-visit follow-up — rate, recover, and rebook',
  'How did your service go? I\'d love a quick rating and any feedback.': 'How did your eye test go? I\'d love a quick rating and any feedback.',
  'Not great — the technician ran late and missed a spot.': 'Not great — the optician ran late and skipped the frame fitting.',
  'I\'m so sorry to hear that — I can send someone back to make it right. When works for you?': 'I\'m so sorry to hear that — I can send someone back to fit the frames. When works for you?',
  'Thanks! Anytime Tuesday morning would be great.': 'Thanks! Anytime Tuesday morning would be great.',
  'Done — you\'re booked for Tuesday at 9am.': 'Done — you\'re booked for Tuesday at 9am.',
  'Reading rating and sentiment': 'Reading rating and sentiment',
  'Recalling completed job': 'Recalling the completed visit',
  'Recovery visit booked — Tuesday 9am': 'Recovery visit booked — Tuesday 9am',
  'The completed job, service rating, next steps': 'The completed visit, rating, next steps',
  'Customer booked, served, and recovered': 'Customer booked, tested, and recovered',
  'Booking & membership systems': 'Booking & membership systems',
  'Dispatch': 'Optician dispatch',
  'Service': 'Eye test',
  'Outreach': 'Outreach',
  'Booking': 'Booking',
  'For consumer services': 'For mobile eye care',
  // generic
  'Sierra Intelligence': 'Sierra Intelligence',
};
